package com.wutsi.platform.payment.provider.mtn

import com.wutsi.platform.payment.core.ErrorCode

enum class MTNErrorCode(val paymentErrorCode: ErrorCode) {
    PAYEE_NOT_FOUND(ErrorCode.PAYEE_NOT_FOUND),
    PAYER_NOT_FOUND(ErrorCode.PAYER_NOT_FOUND),
    NOT_ALLOWED(ErrorCode.NOT_ALLOWED),
    NOT_ALLOWED_TARGET_ENVIRONMENT(ErrorCode.NOT_ALLOWED_TARGET_ENVIRONMENT),
    INVALID_CALLBACK_URL_HOST(ErrorCode.INVALID_CALLBACK_URL_HOST),
    INVALID_CURRENCY(ErrorCode.INVALID_CURRENCY),
    SERVICE_UNAVAILABLE(ErrorCode.SERVICE_UNAVAILABLE),
    INTERNAL_PROCESSING_ERROR(ErrorCode.INTERNAL_PROCESSING_ERROR),
    NOT_ENOUGH_FUNDS(ErrorCode.NOT_ENOUGH_FUNDS),
    PAYER_LIMIT_REACHED(ErrorCode.PAYER_LIMIT_REACHED),
    PAYEE_NOT_ALLOWED_TO_RECEIVE(ErrorCode.PAYEE_NOT_ALLOWED_TO_RECEIVE),
    PAYMENT_NOT_APPROVED(ErrorCode.PAYMENT_NOT_APPROVED),
    RESOURCE_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND),
    APPROVAL_REJECTED(ErrorCode.APPROVAL_REJECTED),
    EXPIRED(ErrorCode.EXPIRED),
    TRANSACTION_CANCELED(ErrorCode.TRANSACTION_CANCELED),
    RESOURCE_ALREADY_EXIST(ErrorCode.RESOURCE_ALREADY_EXIST)
}
